# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1451, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontal = QtWidgets.QHBoxLayout()
        self.horizontal.setObjectName("horizontal")
        self.octavo1 = QtWidgets.QVBoxLayout()
        self.octavo1.setObjectName("octavo1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.part_1 = QtWidgets.QLineEdit(self.frame)
        self.part_1.setObjectName("part_1")
        self.horizontalLayout.addWidget(self.part_1)
        self.win_1 = QtWidgets.QPushButton(self.frame)
        self.win_1.setObjectName("win_1")
        self.horizontalLayout.addWidget(self.win_1)
        self.octavo1.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.part_2 = QtWidgets.QLineEdit(self.frame_2)
        self.part_2.setObjectName("part_2")
        self.horizontalLayout_2.addWidget(self.part_2)
        self.win_2 = QtWidgets.QPushButton(self.frame_2)
        self.win_2.setObjectName("win_2")
        self.horizontalLayout_2.addWidget(self.win_2)
        self.octavo1.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.octavo1.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.part_3 = QtWidgets.QLineEdit(self.frame_3)
        self.part_3.setObjectName("part_3")
        self.horizontalLayout_3.addWidget(self.part_3)
        self.win_3 = QtWidgets.QPushButton(self.frame_3)
        self.win_3.setObjectName("win_3")
        self.horizontalLayout_3.addWidget(self.win_3)
        self.octavo1.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.part_4 = QtWidgets.QLineEdit(self.frame_4)
        self.part_4.setObjectName("part_4")
        self.horizontalLayout_4.addWidget(self.part_4)
        self.win_4 = QtWidgets.QPushButton(self.frame_4)
        self.win_4.setObjectName("win_4")
        self.horizontalLayout_4.addWidget(self.win_4)
        self.octavo1.addWidget(self.frame_4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.octavo1.addWidget(self.line_2)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.part_5 = QtWidgets.QLineEdit(self.frame_5)
        self.part_5.setObjectName("part_5")
        self.horizontalLayout_5.addWidget(self.part_5)
        self.win_5 = QtWidgets.QPushButton(self.frame_5)
        self.win_5.setObjectName("win_5")
        self.horizontalLayout_5.addWidget(self.win_5)
        self.octavo1.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.part_6 = QtWidgets.QLineEdit(self.frame_6)
        self.part_6.setObjectName("part_6")
        self.horizontalLayout_6.addWidget(self.part_6)
        self.win_6 = QtWidgets.QPushButton(self.frame_6)
        self.win_6.setObjectName("win_6")
        self.horizontalLayout_6.addWidget(self.win_6)
        self.octavo1.addWidget(self.frame_6)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.octavo1.addWidget(self.line_3)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.part_7 = QtWidgets.QLineEdit(self.frame_7)
        self.part_7.setObjectName("part_7")
        self.horizontalLayout_7.addWidget(self.part_7)
        self.win_7 = QtWidgets.QPushButton(self.frame_7)
        self.win_7.setObjectName("win_7")
        self.horizontalLayout_7.addWidget(self.win_7)
        self.octavo1.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.part_8 = QtWidgets.QLineEdit(self.frame_8)
        self.part_8.setObjectName("part_8")
        self.horizontalLayout_8.addWidget(self.part_8)
        self.win_8 = QtWidgets.QPushButton(self.frame_8)
        self.win_8.setObjectName("win_8")
        self.horizontalLayout_8.addWidget(self.win_8)
        self.octavo1.addWidget(self.frame_8)
        self.horizontal.addLayout(self.octavo1)
        self.cuartos = QtWidgets.QVBoxLayout()
        self.cuartos.setObjectName("cuartos")
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.next_stage1 = QtWidgets.QLineEdit(self.frame_17)
        self.next_stage1.setObjectName("next_stage1")
        self.horizontalLayout_17.addWidget(self.next_stage1)
        self.next_stageBTN_1 = QtWidgets.QPushButton(self.frame_17)
        self.next_stageBTN_1.setObjectName("next_stageBTN_1")
        self.horizontalLayout_17.addWidget(self.next_stageBTN_1)
        self.cuartos.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.centralwidget)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.next_stage1_2 = QtWidgets.QLineEdit(self.frame_18)
        self.next_stage1_2.setObjectName("next_stage1_2")
        self.horizontalLayout_18.addWidget(self.next_stage1_2)
        self.next_stageBTN_2 = QtWidgets.QPushButton(self.frame_18)
        self.next_stageBTN_2.setObjectName("next_stageBTN_2")
        self.horizontalLayout_18.addWidget(self.next_stageBTN_2)
        self.cuartos.addWidget(self.frame_18)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.cuartos.addWidget(self.line_7)
        self.frame_19 = QtWidgets.QFrame(self.centralwidget)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.next_stage1_3 = QtWidgets.QLineEdit(self.frame_19)
        self.next_stage1_3.setObjectName("next_stage1_3")
        self.horizontalLayout_19.addWidget(self.next_stage1_3)
        self.next_stageBTN_3 = QtWidgets.QPushButton(self.frame_19)
        self.next_stageBTN_3.setObjectName("next_stageBTN_3")
        self.horizontalLayout_19.addWidget(self.next_stageBTN_3)
        self.cuartos.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.centralwidget)
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.next_stage1_4 = QtWidgets.QLineEdit(self.frame_20)
        self.next_stage1_4.setObjectName("next_stage1_4")
        self.horizontalLayout_20.addWidget(self.next_stage1_4)
        self.next_stageBTN_4 = QtWidgets.QPushButton(self.frame_20)
        self.next_stageBTN_4.setObjectName("next_stageBTN_4")
        self.horizontalLayout_20.addWidget(self.next_stageBTN_4)
        self.cuartos.addWidget(self.frame_20)
        self.horizontal.addLayout(self.cuartos)
        self.semifinal = QtWidgets.QVBoxLayout()
        self.semifinal.setObjectName("semifinal")
        self.frame_25 = QtWidgets.QFrame(self.centralwidget)
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.next_semiFinals = QtWidgets.QLineEdit(self.frame_25)
        self.next_semiFinals.setObjectName("next_semiFinals")
        self.horizontalLayout_25.addWidget(self.next_semiFinals)
        self.next_semifinalsBTN = QtWidgets.QPushButton(self.frame_25)
        self.next_semifinalsBTN.setObjectName("next_semifinalsBTN")
        self.horizontalLayout_25.addWidget(self.next_semifinalsBTN)
        self.semifinal.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.centralwidget)
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.next_semiFinals_2 = QtWidgets.QLineEdit(self.frame_26)
        self.next_semiFinals_2.setObjectName("next_semiFinals_2")
        self.horizontalLayout_26.addWidget(self.next_semiFinals_2)
        self.next_semifinalsBTN_2 = QtWidgets.QPushButton(self.frame_26)
        self.next_semifinalsBTN_2.setObjectName("next_semifinalsBTN_2")
        self.horizontalLayout_26.addWidget(self.next_semifinalsBTN_2)
        self.semifinal.addWidget(self.frame_26)
        self.horizontal.addLayout(self.semifinal)
        self.final_2 = QtWidgets.QVBoxLayout()
        self.final_2.setObjectName("final_2")
        self.frame_29 = QtWidgets.QFrame(self.centralwidget)
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.btn_final = QtWidgets.QPushButton(self.frame_29)
        self.btn_final.setObjectName("btn_final")
        self.horizontalLayout_29.addWidget(self.btn_final)
        self.final_part = QtWidgets.QLineEdit(self.frame_29)
        self.final_part.setObjectName("final_part")
        self.horizontalLayout_29.addWidget(self.final_part)
        self.final_part2 = QtWidgets.QLineEdit(self.frame_29)
        self.final_part2.setObjectName("final_part2")
        self.horizontalLayout_29.addWidget(self.final_part2)
        self.btn_final2 = QtWidgets.QPushButton(self.frame_29)
        self.btn_final2.setObjectName("btn_final2")
        self.horizontalLayout_29.addWidget(self.btn_final2)
        self.final_2.addWidget(self.frame_29)
        self.horizontal.addLayout(self.final_2)
        self.semifinal_2 = QtWidgets.QVBoxLayout()
        self.semifinal_2.setObjectName("semifinal_2")
        self.frame_27 = QtWidgets.QFrame(self.centralwidget)
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.next_semiFinals_3 = QtWidgets.QLineEdit(self.frame_27)
        self.next_semiFinals_3.setObjectName("next_semiFinals_3")
        self.horizontalLayout_27.addWidget(self.next_semiFinals_3)
        self.next_semifinalsBTN_3 = QtWidgets.QPushButton(self.frame_27)
        self.next_semifinalsBTN_3.setObjectName("next_semifinalsBTN_3")
        self.horizontalLayout_27.addWidget(self.next_semifinalsBTN_3)
        self.semifinal_2.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.centralwidget)
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.next_semiFinals_4 = QtWidgets.QLineEdit(self.frame_28)
        self.next_semiFinals_4.setObjectName("next_semiFinals_4")
        self.horizontalLayout_28.addWidget(self.next_semiFinals_4)
        self.next_semifinalsBTN_4 = QtWidgets.QPushButton(self.frame_28)
        self.next_semifinalsBTN_4.setObjectName("next_semifinalsBTN_4")
        self.horizontalLayout_28.addWidget(self.next_semifinalsBTN_4)
        self.semifinal_2.addWidget(self.frame_28)
        self.horizontal.addLayout(self.semifinal_2)
        self.cuartos2 = QtWidgets.QVBoxLayout()
        self.cuartos2.setObjectName("cuartos2")
        self.frame_21 = QtWidgets.QFrame(self.centralwidget)
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.next_stage1_5 = QtWidgets.QLineEdit(self.frame_21)
        self.next_stage1_5.setObjectName("next_stage1_5")
        self.horizontalLayout_21.addWidget(self.next_stage1_5)
        self.next_stageBTN_5 = QtWidgets.QPushButton(self.frame_21)
        self.next_stageBTN_5.setObjectName("next_stageBTN_5")
        self.horizontalLayout_21.addWidget(self.next_stageBTN_5)
        self.cuartos2.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.centralwidget)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.next_stage1_6 = QtWidgets.QLineEdit(self.frame_22)
        self.next_stage1_6.setObjectName("next_stage1_6")
        self.horizontalLayout_22.addWidget(self.next_stage1_6)
        self.next_stageBTN_6 = QtWidgets.QPushButton(self.frame_22)
        self.next_stageBTN_6.setObjectName("next_stageBTN_6")
        self.horizontalLayout_22.addWidget(self.next_stageBTN_6)
        self.cuartos2.addWidget(self.frame_22)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.cuartos2.addWidget(self.line_8)
        self.frame_23 = QtWidgets.QFrame(self.centralwidget)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.next_stage1_7 = QtWidgets.QLineEdit(self.frame_23)
        self.next_stage1_7.setObjectName("next_stage1_7")
        self.horizontalLayout_23.addWidget(self.next_stage1_7)
        self.next_stageBTN_7 = QtWidgets.QPushButton(self.frame_23)
        self.next_stageBTN_7.setObjectName("next_stageBTN_7")
        self.horizontalLayout_23.addWidget(self.next_stageBTN_7)
        self.cuartos2.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.centralwidget)
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.next_stage1_8 = QtWidgets.QLineEdit(self.frame_24)
        self.next_stage1_8.setObjectName("next_stage1_8")
        self.horizontalLayout_24.addWidget(self.next_stage1_8)
        self.next_stageBTN_8 = QtWidgets.QPushButton(self.frame_24)
        self.next_stageBTN_8.setObjectName("next_stageBTN_8")
        self.horizontalLayout_24.addWidget(self.next_stageBTN_8)
        self.cuartos2.addWidget(self.frame_24)
        self.horizontal.addLayout(self.cuartos2)
        self.octavo2 = QtWidgets.QVBoxLayout()
        self.octavo2.setObjectName("octavo2")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.part_9 = QtWidgets.QLineEdit(self.frame_9)
        self.part_9.setObjectName("part_9")
        self.horizontalLayout_9.addWidget(self.part_9)
        self.win_9 = QtWidgets.QPushButton(self.frame_9)
        self.win_9.setObjectName("win_9")
        self.horizontalLayout_9.addWidget(self.win_9)
        self.octavo2.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.part_10 = QtWidgets.QLineEdit(self.frame_10)
        self.part_10.setObjectName("part_10")
        self.horizontalLayout_10.addWidget(self.part_10)
        self.win_10 = QtWidgets.QPushButton(self.frame_10)
        self.win_10.setObjectName("win_10")
        self.horizontalLayout_10.addWidget(self.win_10)
        self.octavo2.addWidget(self.frame_10)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.octavo2.addWidget(self.line_4)
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.part_11 = QtWidgets.QLineEdit(self.frame_11)
        self.part_11.setObjectName("part_11")
        self.horizontalLayout_11.addWidget(self.part_11)
        self.win_11 = QtWidgets.QPushButton(self.frame_11)
        self.win_11.setObjectName("win_11")
        self.horizontalLayout_11.addWidget(self.win_11)
        self.octavo2.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.part_12 = QtWidgets.QLineEdit(self.frame_12)
        self.part_12.setObjectName("part_12")
        self.horizontalLayout_12.addWidget(self.part_12)
        self.win_12 = QtWidgets.QPushButton(self.frame_12)
        self.win_12.setObjectName("win_12")
        self.horizontalLayout_12.addWidget(self.win_12)
        self.octavo2.addWidget(self.frame_12)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.octavo2.addWidget(self.line_5)
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.part_13 = QtWidgets.QLineEdit(self.frame_13)
        self.part_13.setObjectName("part_13")
        self.horizontalLayout_13.addWidget(self.part_13)
        self.win_13 = QtWidgets.QPushButton(self.frame_13)
        self.win_13.setObjectName("win_13")
        self.horizontalLayout_13.addWidget(self.win_13)
        self.octavo2.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.part_14 = QtWidgets.QLineEdit(self.frame_14)
        self.part_14.setObjectName("part_14")
        self.horizontalLayout_14.addWidget(self.part_14)
        self.win_14 = QtWidgets.QPushButton(self.frame_14)
        self.win_14.setObjectName("win_14")
        self.horizontalLayout_14.addWidget(self.win_14)
        self.octavo2.addWidget(self.frame_14)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.octavo2.addWidget(self.line_6)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.part_15 = QtWidgets.QLineEdit(self.frame_15)
        self.part_15.setObjectName("part_15")
        self.horizontalLayout_15.addWidget(self.part_15)
        self.win_15 = QtWidgets.QPushButton(self.frame_15)
        self.win_15.setObjectName("win_15")
        self.horizontalLayout_15.addWidget(self.win_15)
        self.octavo2.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.part_16 = QtWidgets.QLineEdit(self.frame_16)
        self.part_16.setObjectName("part_16")
        self.horizontalLayout_16.addWidget(self.part_16)
        self.win_16 = QtWidgets.QPushButton(self.frame_16)
        self.win_16.setObjectName("win_16")
        self.horizontalLayout_16.addWidget(self.win_16)
        self.octavo2.addWidget(self.frame_16)
        self.horizontal.addLayout(self.octavo2)
        self.gridLayout.addLayout(self.horizontal, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1451, 25))
        self.menubar.setObjectName("menubar")
        self.menuIntegrantes = QtWidgets.QMenu(self.menubar)
        self.menuIntegrantes.setObjectName("menuIntegrantes")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Participans = QtWidgets.QAction(MainWindow)
        self.actionAdd_Participans.setObjectName("actionAdd_Participans")
        self.menuIntegrantes.addAction(self.actionAdd_Participans)
        self.menubar.addAction(self.menuIntegrantes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.win_1.setText(_translate("MainWindow", "Next Phase"))
        self.win_2.setText(_translate("MainWindow", "Next Phase"))
        self.win_3.setText(_translate("MainWindow", "Next Phase"))
        self.win_4.setText(_translate("MainWindow", "Next Phase"))
        self.win_5.setText(_translate("MainWindow", "Next Phase"))
        self.win_6.setText(_translate("MainWindow", "Next Phase"))
        self.win_7.setText(_translate("MainWindow", "Next Phase"))
        self.win_8.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_1.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_2.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_3.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_4.setText(_translate("MainWindow", "Next Phase"))
        self.next_semifinalsBTN.setText(_translate("MainWindow", "Next Phase"))
        self.next_semifinalsBTN_2.setText(_translate("MainWindow", "Next Phase"))
        self.btn_final.setText(_translate("MainWindow", "Final Win"))
        self.btn_final2.setText(_translate("MainWindow", "Final Win"))
        self.next_semifinalsBTN_3.setText(_translate("MainWindow", "Next Phase"))
        self.next_semifinalsBTN_4.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_5.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_6.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_7.setText(_translate("MainWindow", "Next Phase"))
        self.next_stageBTN_8.setText(_translate("MainWindow", "Next Phase"))
        self.win_9.setText(_translate("MainWindow", "Next Phase"))
        self.win_10.setText(_translate("MainWindow", "Next Phase"))
        self.win_11.setText(_translate("MainWindow", "Next Phase"))
        self.win_12.setText(_translate("MainWindow", "Next Phase"))
        self.win_13.setText(_translate("MainWindow", "Next Phase"))
        self.win_14.setText(_translate("MainWindow", "Next Phase"))
        self.win_15.setText(_translate("MainWindow", "Next Phase"))
        self.win_16.setText(_translate("MainWindow", "Next Phase"))
        self.menuIntegrantes.setTitle(_translate("MainWindow", "Participans"))
        self.actionAdd_Participans.setText(_translate("MainWindow", "Add Participans"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

