# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'participant_raw.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt, QTimer
import Data.ping_pong_db as db
import Data.pool_db as pool_db
import Data.uno_db as uno_db

class Ui_Window_Participans(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.participant1 = QtWidgets.QLineEdit(self.frame)
        self.participant1.setObjectName("participant1")
        self.gridLayout.addWidget(self.participant1, 1, 0, 1, 1)
        self.participant_9 = QtWidgets.QLineEdit(self.frame)
        self.participant_9.setText("")
        self.participant_9.setObjectName("participant_9")
        self.gridLayout.addWidget(self.participant_9, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.participant_2 = QtWidgets.QLineEdit(self.frame)
        self.participant_2.setObjectName("participant_2")
        self.gridLayout.addWidget(self.participant_2, 3, 0, 1, 1)
        self.participant_10 = QtWidgets.QLineEdit(self.frame)
        self.participant_10.setText("")
        self.participant_10.setObjectName("participant_10")
        self.gridLayout.addWidget(self.participant_10, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.participant_3 = QtWidgets.QLineEdit(self.frame)
        self.participant_3.setText("")
        self.participant_3.setObjectName("participant_3")
        self.gridLayout.addWidget(self.participant_3, 5, 0, 1, 1)
        self.participant_11 = QtWidgets.QLineEdit(self.frame)
        self.participant_11.setText("")
        self.participant_11.setObjectName("participant_11")
        self.gridLayout.addWidget(self.participant_11, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 6, 1, 2, 1)
        self.participant_4 = QtWidgets.QLineEdit(self.frame)
        self.participant_4.setText("")
        self.participant_4.setObjectName("participant_4")
        self.gridLayout.addWidget(self.participant_4, 7, 0, 2, 1)
        self.participant_22 = QtWidgets.QLineEdit(self.frame)
        self.participant_22.setText("")
        self.participant_22.setObjectName("participant_22")
        self.gridLayout.addWidget(self.participant_22, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 9, 1, 2, 1)
        self.participant_5 = QtWidgets.QLineEdit(self.frame)
        self.participant_5.setText("")
        self.participant_5.setObjectName("participant_5")
        self.gridLayout.addWidget(self.participant_5, 10, 0, 2, 1)
        self.participant_23 = QtWidgets.QLineEdit(self.frame)
        self.participant_23.setText("")
        self.participant_23.setObjectName("participant_23")
        self.gridLayout.addWidget(self.participant_23, 11, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 12, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 12, 1, 1, 1)
        self.participant_6 = QtWidgets.QLineEdit(self.frame)
        self.participant_6.setText("")
        self.participant_6.setObjectName("participant_6")
        self.gridLayout.addWidget(self.participant_6, 13, 0, 1, 1)
        self.participant_24 = QtWidgets.QLineEdit(self.frame)
        self.participant_24.setText("")
        self.participant_24.setObjectName("participant_24")
        self.gridLayout.addWidget(self.participant_24, 13, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 14, 0, 2, 1)
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 14, 1, 1, 1)
        self.participant_25 = QtWidgets.QLineEdit(self.frame)
        self.participant_25.setText("")
        self.participant_25.setObjectName("participant_25")
        self.gridLayout.addWidget(self.participant_25, 15, 1, 2, 1)
        self.participant_7 = QtWidgets.QLineEdit(self.frame)
        self.participant_7.setText("")
        self.participant_7.setObjectName("participant_7")
        self.gridLayout.addWidget(self.participant_7, 16, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 17, 0, 2, 1)
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 17, 1, 1, 1)
        self.participant_26 = QtWidgets.QLineEdit(self.frame)
        self.participant_26.setText("")
        self.participant_26.setObjectName("participant_26")
        self.gridLayout.addWidget(self.participant_26, 18, 1, 2, 1)
        self.participant_8 = QtWidgets.QLineEdit(self.frame)
        self.participant_8.setText("")
        self.participant_8.setObjectName("participant_8")
        self.gridLayout.addWidget(self.participant_8, 19, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_ping_pong = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_ping_pong.setObjectName("rb_ping_pong")
        self.horizontalLayout_2.addWidget(self.rb_ping_pong)
        self.rb_uno = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_uno.setObjectName("rb_uno")
        self.horizontalLayout_2.addWidget(self.rb_uno)
        self.rb_pool = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_pool.setObjectName("rb_pool")
        self.horizontalLayout_2.addWidget(self.rb_pool)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        """ ============ FUNCIONALIDAD DE LA VENTANA ============ """
        #Call the function to create the database
        

        self.btn_add.clicked.connect(self.generate_databases)

    def generate_databases(self):

        if self.rb_ping_pong.isChecked():
            db.participant_data()
            self.add_participant()

        if self.rb_pool.isChecked():
            pool_db.participant_data()
            self.add_pool_participant()
        
        if self.rb_uno.isChecked():
            uno_db.participant_data()
            self.add_uno_participant()

    def add_uno_participant(self):
        uno_db.add_name(self.participant1.text())
        uno_db.add_name(self.participant_2.text())
        uno_db.add_name(self.participant_3.text())
        uno_db.add_name(self.participant_4.text())
        uno_db.add_name(self.participant_5.text())
        uno_db.add_name(self.participant_6.text())
        uno_db.add_name(self.participant_7.text())
        uno_db.add_name(self.participant_8.text())
        uno_db.add_name(self.participant_9.text())
        uno_db.add_name(self.participant_10.text())
        uno_db.add_name(self.participant_11.text())
        uno_db.add_name(self.participant_22.text())
        uno_db.add_name(self.participant_23.text())
        uno_db.add_name(self.participant_24.text())
        uno_db.add_name(self.participant_25.text())
        uno_db.add_name(self.participant_26.text())

        msg = QMessageBox()
        msg.setWindowTitle("Players Registered to Uno Successfully")
        msg.setText("Players Added to queue successfully")
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def add_pool_participant(self):
        pool_db.add_name(self.participant1.text())
        pool_db.add_name(self.participant_2.text())
        pool_db.add_name(self.participant_3.text())
        pool_db.add_name(self.participant_4.text())
        pool_db.add_name(self.participant_5.text())
        pool_db.add_name(self.participant_6.text())
        pool_db.add_name(self.participant_7.text())
        pool_db.add_name(self.participant_8.text())
        pool_db.add_name(self.participant_9.text())
        pool_db.add_name(self.participant_10.text())
        pool_db.add_name(self.participant_11.text())
        pool_db.add_name(self.participant_22.text())
        pool_db.add_name(self.participant_23.text())
        pool_db.add_name(self.participant_24.text())
        pool_db.add_name(self.participant_25.text())
        pool_db.add_name(self.participant_26.text())

        msg = QMessageBox()
        msg.setWindowTitle("Players Registered to Pool Successfully")
        msg.setText("Players Added to queue successfully")
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def add_participant(self):
        db.add_name(self.participant1.text())
        db.add_name(self.participant_2.text())
        db.add_name(self.participant_3.text())
        db.add_name(self.participant_4.text())
        db.add_name(self.participant_5.text())
        db.add_name(self.participant_6.text())
        db.add_name(self.participant_7.text())
        db.add_name(self.participant_8.text())
        db.add_name(self.participant_9.text())
        db.add_name(self.participant_10.text())
        db.add_name(self.participant_11.text())
        db.add_name(self.participant_22.text())
        db.add_name(self.participant_23.text())
        db.add_name(self.participant_24.text())
        db.add_name(self.participant_25.text())
        db.add_name(self.participant_26.text())

        msg = QMessageBox()
        msg.setWindowTitle("Players Registered to Ping Pong Successfully")
        msg.setText("Players Added to queue successfully")
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Participant"))
        self.label.setText(_translate("MainWindow", "Participant 1"))
        self.label_9.setText(_translate("MainWindow", "Participant 9"))
        self.label_2.setText(_translate("MainWindow", "Participant 2"))
        self.label_10.setText(_translate("MainWindow", "Participant 10"))
        self.label_3.setText(_translate("MainWindow", "Participant 3"))
        self.label_11.setText(_translate("MainWindow", "Participant 11"))
        self.label_4.setText(_translate("MainWindow", "Participant 4"))
        self.label_23.setText(_translate("MainWindow", "Participant 12"))
        self.label_5.setText(_translate("MainWindow", "Participant 5"))
        self.label_24.setText(_translate("MainWindow", "Participant 13"))
        self.label_6.setText(_translate("MainWindow", "Participant 6"))
        self.label_25.setText(_translate("MainWindow", "Participant 14"))
        self.label_7.setText(_translate("MainWindow", "Participant 7"))
        self.label_26.setText(_translate("MainWindow", "Participant 15"))
        self.label_8.setText(_translate("MainWindow", "Participant 8"))
        self.label_27.setText(_translate("MainWindow", "Participant 16"))
        self.rb_ping_pong.setText(_translate("MainWindow", "Ping Pong"))
        self.rb_uno.setText(_translate("MainWindow", "Uno"))
        self.rb_pool.setText(_translate("MainWindow", "Pool"))
        self.btn_add.setText(_translate("MainWindow", "Load Participans"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

